# Generated by Django 3.2.5 on 2026-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20260401_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='discount_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
