# Generated by Django 4.2.29 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
