# Generated by Django 4.2.29 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
