from django.urls import path
from .views import *

urlpatterns = [
    path('categories/', cats, name='all-cats'),
    path('categories/reorder/', cats_reorder, name='cats-reorder'),
    path('categories/create/', cat_create, name='cat-create'),
    path('categories/edit/', cat_edit_list, name='cat-edit-list'),
    path('categories/<int:cat_id>/edit/', cat_edit, name='cat-edit'),
    path('categories/<int:cat_id>/delete/', cat_delete, name='cat-delete'),
    path('categories/<int:cat_id>/products/', cat_products, name='cat-products'),
    path('products/', subs, name='all-sub-cats'),
    path('search-api/', live_search, name='live-search'),
    path('products/<int:sub_id>/', sub_detail, name='sub-detail'),
    path('products/<int:sub_id>/favorite/', toggle_favorite, name='toggle-favorite'),
    path('products/<int:sub_id>/favorite-guest/', toggle_favorite_guest, name='toggle-favorite-guest'),
    path('favorites/', favorites, name='favorites'),
    path('favorites/reorder/', favorites_reorder, name='favorites-reorder'),
    path('products/edit/', sub_edit_list, name='sub-edit-list'),
    path('products/<int:sub_id>/edit/', sub_edit, name='sub-edit'),
    path('products/<int:sub_id>/delete/', sub_delete, name='sub-delete'),
    path('products/<int:sub_id>/add-to-cart/', add_to_cart, name='add-to-cart'),
    path('products/<int:sub_id>/add-to-cart-guest/', add_to_cart_guest, name='add-to-cart-guest'),
    path('products/<int:sub_id>/buy-now/', buy_now, name='buy-now'),
    path('products/<int:sub_id>/buy-now-guest/', buy_now_guest, name='buy-now-guest'),
    path('cart/', cart_view, name='cart'),
    path('cart/<int:item_id>/<str:action>/', update_cart, name='update-cart'),
    path('orders/<int:order_id>/<str:status>/', order_update_status, name='order-update-status'),
    path('products/create/', create, name='sub-create'),
]
