# Generated by Django 4.2.29 on 2026-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_homecontent_hero_photos_homesection_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
