# Generated by Django 4.2.29 on 2026-04-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_landingcontent_favicon_landingcontent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='carousel_interval',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='HomeCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/carousel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='app.homecontent')),
            ],
        ),
    ]
