# Generated by Django 4.2.29 on 2026-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='background_media',
            field=models.FileField(blank=True, null=True, upload_to='branding/backgrounds/'),
        ),
    ]
