# Generated by Django 4.2.29 on 2026-04-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_landingcontent_background_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='background_media_mobile',
            field=models.FileField(blank=True, null=True, upload_to='branding/backgrounds/'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='background_opacity',
            field=models.FloatField(default=0.35),
        ),
    ]
